version: '3.8'

services:
  backend:
    build: .
    # Starts the FastAPI server and broadcasts on the Linux network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/app
  frontend:
    build: .
    command: streamlit run app/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - 8501:8501
    # This ensures the 'Kitchen' is ready before the 'Waiter' starts
    depends_on:
      - backend
    volumes:
      - .:/app